version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    environment:
      discovery.type: single-node

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"