kafka:
  brokers:
    - kafka1:9092
    - kafka2:9092
  topic: logs
  group_id: log-processors
  security:
    tls:
      enabled: true
      ca_file: /secrets/ca.pem
      cert_file: /secrets/client.pem
      key_file: /secrets/client.key
    sasl:
      enabled: true
      username: admin
      password: secure-password

elastic:
  addresses:
    - http://elasticsearch:9200
  username: elastic
  password: changeme
  index: logs

s3:
  region: us-west-2
  bucket: log-archive
  access_key: AKIA...
  secret_key: ...

monitoring:
  prometheus:
    enabled: true
    port: 2112